name: Package

on:
  push:
    tags:
      - 'v*'
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Build wheel
        run: |
          python -m pip install --upgrade pip setuptools wheel &&
          python setup.py bdist_wheel &&
          mkdir -p out/wheels/CLIP/${{ github.ref_name }} &&
          cp -r dist/* out/wheels/CLIP/${{ github.ref_name }}/

      - name: Azure Blob Storage Upload
        # You may pin to the exact commit or the version.
        # uses: bacongobbler/azure-blob-storage-upload@50f7d898b7697e864130ea04c303ca38b5751c50
        uses: bacongobbler/azure-blob-storage-upload@v3.0.0
        with:
          # The connection string for the storage account. Used if value is set. Either connection_string or sas_token must be supplied
          # connection_string: # optional
          # The shared access signature token for the storage account. Either connection_string or sas_token must be supplied
          sas_token: ${{ secrets.PACKAGE_RELEASE_AZURE_CREDENTIALS }}
          # The name of the storage account. Required if sas_token is used
          account_name: ${{ secrets.PACKAGE_RELEASE_AZURE_STORAGE_ACCOUNT }}
          # The name of the storage account container these assets will be uploaded to
          container_name: ${{ secrets.PACKAGE_RELEASE_AZURE_CONTAINER_NAME }}
          # The name of the directory you want to upload
          source_dir: out
          # Extra arguments that can be passed to `az storage blob upload-batch|sync`. Useful for passing flags like `--pattern` or `--destination-path`
          # extra_args: # optional
          # Use `az storage blob sync` to synchronize blobs recursively
          # sync: # optional
          # Overwrite existing files in the destination container. Defaults to false
          overwrite: true 
